# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "php:8.3"

# Configuration of the build of the application.
build:
  flavor: composer

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: "db:mysql"

# The configuration of app when it is exposed to the web.
web:
  locations:
    "/":
      # The public directory of the app, relative to its root.
      root: "web"
      # The front-controller script to send non-static requests to.
      passthru: "/index.php"
      # Wordpress has multiple roots (wp-admin) so the following is required
      index:
        - "index.php"
      # The number of seconds whitelisted (static) content should be cached.
      expires: 600
      scripts: true
      allow: true
      rules:
        ^/composer\.json:
          allow: false
        ^/license\.txt$:
          allow: false
        ^/readme\.html$:
          allow: false
        # expiry time for static content
        '\.(mp4|jpe?g|png|gif|svgz?|map|ico|bmp|eot|woff2?|otf|ttf)$':
          expires: 1w
        '\.(css|js)$':
          expires: 1w
        '\.(html|php)$':
            expires: 600s
    "/wp-content/cache":
      root: "web/wp-content/cache"
      scripts: false
      allow: false
    "/wp-content/breeze-config":
      root: "web/wp-content/breeze-config"
      scripts: false
      allow: false
    "/wp-content/cache-config":
      root: "web/wp-content/cache-config"
      scripts: false
      allow: false
    "/wp-content/uploads":
      root: "web/wp-content/uploads"
      scripts: false
      allow: false
      rules:
          # Allow access to common static files.
          '(?<!\-lock)\.(?i:jpe?g|gif|png|svg|bmp|ico|css|js(?:on)?|eot|ttf|woff|woff2|pdf|docx?|xlsx?|pp[st]x?|psd|odt|key|mp[2-5g]|m4[av]|og[gv]|wav|mov|wm[av]|avi|3g[p2])$':
              allow: true
              expires: 1w
    "/xmlrpc.php":
      root: "web"
      allow: false
      scripts: false
    "/360/vtourdata":
      root: "web/360/vtourdata"
      scripts: true
      allow: true
      index:
        - "index.html"

# The size of the persistent disk of the application (in MB).
disk: 13500

# Dependencies needed for build - yarn, bower, gulp, ruby etc.
dependencies:
  nodejs:
    yarn: "^1.22.4"
  php:
    composer/composer: '2.2.12'
    wp-cli/wp-cli: "^2.5.0"

# The mounts that will be performed when the package is deployed.
mounts:
  "web/wp-content/cache": "shared:files/cache"
  "web/wp-content/uploads": "shared:files/uploads"
  "web/360/vtourdata": "shared:files/vtourdata"
  "web/sites": "shared:files/sites"
  "web/wp-content/cache-config":
    source: local
    source_path: cache-config
  "web/wp-content/breeze-config":
    source: local
    source_path: breeze-config

# runtime:
#   extensions:
#     - newrelic

hooks:
  build: |
    set -e
    composer build
    composer check-updates
    curl -fsSL https://raw.githubusercontent.com/platformsh/cli/main/installer.sh | bash
    ln -sf /app/web/wp-content/cache-config/advanced-cache.php /app/web/wp-content/advanced-cache.php
  deploy: |
    # Ensure the target file exists if it doesn't
    if [ ! -f /app/web/wp-content/cache-config/advanced-cache.php ]; then
        touch /app/web/wp-content/cache-config/advanced-cache.php
    fi

variables:
  php:
    short_open_tag: on
    # https://docs.platform.sh/languages/php/tuning.html
    disable_functions: "pcntl_exec,pcntl_fork"
    opcache.enable: 1
    opcache.enable_cli: 1
    opcache.revalidate_freq: 0
    opcache.validate_timestamps: 1
    opcache.max_accelerated_files: 22000
    opcache.memory_consumption: 192
    opcache.max_wasted_percentage: 10
    opcache.interned_strings_buffer: 16
    opcache.fast_shutdown: 1
    opcache.jit_buffer_size: 500000000
    opcache.jit: 1235
    memory_limit: 256M
    max_execution_time: 120
    display_errors: Off
    upload_max_filesize: 64M
    post_max_size: 64M
    zlib.output_compression: "On"
    zlib.output_compression_level: 5

  # Environment variables to use on platform.sh
  env:
    #Arguments to connect to internal database: i.e. mysql $DATABASE
    DATABASE: -h database.internal -P 3306 -u user main
    # Set NodeJS version
    NODE_VERSION: 22.14.0
    # Set NVM version
    NVM_VERSION: 0.35.2
    # Flip this switch to use in your build cmds to enable development build on platform. 
    PRODUCTION: yes 

crons:
  # Backup the database everyday at 8am
  snapshot:
    spec: "0 8 * * *"
    cmd: |
      if [ "$PLATFORM_BRANCH" = main ]; then
          platform snapshot:create --yes --no-wait
      fi
  # Optimize the database everyday at 9am
  analyze:
    spec: "0 9 * * *"
    cmd: |
        mysqlcheck $DATABASE; 
        mysqloptimize $DATABASE; 
        mysqlanalyze $DATABASE;
        wp transient delete --all --quiet;

  # Force a redeploy at 10am (UTC) on the 1st and 15th of every month.
  redeploy:
    spec: "0 10 1,15 * *"
    cmd: |
      if [ "$PLATFORM_BRANCH" = main ]; then
          platform redeploy --yes --no-wait
      fi

  # Run WordPress cron every 15 minutes
  # NOTE: DISABLE_WP_CRON has been turned on wp-config-platform.php 
  # uncomment lines below to enable 
  # wordpress:
  #   spec: "*/15 * * * *"
  #   cmd: |
  #     php ${PLATFORM_DOCUMENT_ROOT}/wp-cron.php

# Runtime Operations
operations:

  Purge Varnish:
    role: admin
    commands:
      start: curl -X PURGE https://www.dev-54ta5gq-bxdsevwcta6ce.us-4.platformsh.site

  Trigger Rebuild:
    role: admin
    commands:
      start: git commit --allow-empty -m "Trigger rebuild or redeployment" && platform push

