# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "php:8.3"

# Configuration of the build of the application.
build:
  flavor: composer

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: "db:mysql"

# The configuration of app when it is exposed to the web.
web:
  locations:
    "/":
      # The public directory of the app, relative to its root.
      root: "web"
      # The front-controller script to send non-static requests to.
      passthru: "/index.php"
      # Wordpress has multiple roots (wp-admin) so the following is required
      index:
        - "index.php"
      # The number of seconds whitelisted (static) content should be cached.
      expires: 600
      scripts: true
      allow: true
      headers:
        strict-transport-security: "max-age=63072000; includeSubDomains; preload"
        x-content-type-options: "nosniff"
        x-frame-options: "SAMEORIGIN"
        x-xss-protection: "1; mode=block"
        referrer-policy: "strict-origin-when-cross-origin"
        content-security-policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
      rules:
        ################################
        ### CORE ###
        ###############################
        ^/composer\.json:
          allow: false
        ^/license\.txt$:
          allow: false
        ^/readme\.html$:
          allow: false
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true
        ################################
        ### WORDPRESS MULTISITE ###
        ###############################
        # We need to allow requests to wp-login.php to pass through
        # Multisites do not respect the WP_SITEURL constant in wp-config.
        # In addition, directory-based multisites include the virtual directory before the wp-login.php
        '^/([\_0-9a-zA-Z-]+/)?wp-(?<wproot>[a-z\\-]+).php$':
          allow: true
          scripts: true
          passthru: "/wp-$wproot.php"
        # Handle static files (CSS, JS, images) in wp-includes and wp-admin for subdirectory multisites
        # These should be served directly without PHP processing
        '^/([\_0-9a-zA-Z-]+/)?(?<corepath>wp-(admin|includes)/.*\.(css|js|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot))$':
          allow: true
          scripts: false
          passthru: "/$corepath"
          expires: 1y
          headers:
            cache-control: "public, max-age=31536000, immutable"
        # Allows directory-based multisites to still access the wp-admin and wp-includes locations (PHP files)
        '^/([\_0-9a-zA-Z-]+/)?(?<adminrewrite>wp-(admin|includes).*)':
          allow: true
          scripts: true
          passthru: "/$adminrewrite"
        # Handle wp-content for subdirectory multisites
        '^/([\_0-9a-zA-Z-]+)/wp-content/(?<content>.*)':
          allow: true
          scripts: false
          passthru: "/wp-content/$content"
          expires: 1w
        ################################
        ### STATIC CONTENT ###
        ###############################
        # expiry time for static content
        '\.(mp4|jpe?g|png|gif|svgz?|map|ico|bmp|eot|woff2?|otf|ttf)$':
          expires: 1y
          headers:
            cache-control: "public, max-age=31536000, immutable"
        '\.(css|js)$':
          expires: 1y
          headers:
            cache-control: "public, max-age=31536000, immutable"
        '\.(html|php)$':
          expires: 600s
          headers:
            cache-control: "private, max-age=600"
    "/wp-content/cache":
      root: "web/wp-content/cache"
      scripts: false
      allow: false
    "/wp-content/breeze-config":
      root: "web/wp-content/breeze-config"
      scripts: false
      allow: false
    "/wp-content/cache-config":
      root: "web/wp-content/cache-config"
      scripts: false
      allow: false
    "/wp-content/themes":
      root: "web/wp-content/themes"
      scripts: false
      allow: true
      expires: 1y
      headers:
        cache-control: "public, max-age=31536000, immutable"
    "/wp-content/uploads":
      root: "web/wp-content/uploads"
      scripts: false
      allow: false
      rules:
        # Allow access to common static files.
        '(?<!\-lock)\.(?i:jpe?g|gif|png|svg|bmp|ico|css|js(?:on)?|eot|ttf|woff|woff2|pdf|docx?|xlsx?|pp[st]x?|psd|odt|key|mp[2-5g]|m4[av]|og[gv]|wav|mov|wm[av]|avi|3g[p2])$':
          allow: true
          expires: 1y
          headers:
            cache-control: "public, max-age=31536000, immutable"
    "/xmlrpc.php":
      root: "web"
      allow: false
      scripts: false
    "/360/vtourdata":
      root: "web/360/vtourdata"
      scripts: true
      allow: true
      index:
        - "index.html"

# The size of the persistent disk of the application (in MB).
disk: 18432

# Dependencies needed for build - yarn, bower, gulp, ruby etc.
dependencies:
  nodejs:
    yarn: "^1.22.4"
  php:
    composer/composer: "2.2.12"
    wp-cli/wp-cli: "^2.5.0"

# The mounts that will be performed when the package is deployed.
mounts:
  "web/wp-content/cache": "shared:files/cache"
  "web/wp-content/uploads": "shared:files/uploads"
  "web/360/vtourdata": "shared:files/vtourdata"
  "web/sites": "shared:files/sites"
  "web/wp-content/cache-config":
    source: local
    source_path: cache-config
  "web/wp-content/breeze-config":
    source: local
    source_path: breeze-config

# runtime:
#   extensions:
#     - newrelic

hooks:
  build: |
    set -e
    composer build
    composer check-updates
    # Build mmk-bradmicro child theme assets
    if [ -d "web/wp-content/themes/mmk-bradmicro/assets" ]; then
      cd web/wp-content/themes/mmk-bradmicro/assets
      if [ -f "package.json" ]; then
        yarn install
        yarn build
      fi
      cd /app
    fi
    curl -fsSL https://raw.githubusercontent.com/platformsh/cli/main/installer.sh | bash
    ln -sf /app/web/wp-content/cache-config/advanced-cache.php /app/web/wp-content/advanced-cache.php
  deploy: |
    # Ensure the target file exists if it doesn't
    if [ ! -f /app/web/wp-content/cache-config/advanced-cache.php ]; then
        touch /app/web/wp-content/cache-config/advanced-cache.php
    fi

variables:
  php:
    short_open_tag: on
    # https://docs.platform.sh/languages/php/tuning.html
    disable_functions: "pcntl_exec,pcntl_fork"
    opcache.enable: 1
    opcache.enable_cli: 1
    opcache.revalidate_freq: 0
    opcache.validate_timestamps: 1
    opcache.max_accelerated_files: 22000
    opcache.memory_consumption: 192
    opcache.max_wasted_percentage: 10
    opcache.interned_strings_buffer: 16
    opcache.fast_shutdown: 1
    opcache.jit_buffer_size: 500000000
    opcache.jit: 1235
    memory_limit: 256M
    max_execution_time: 120
    display_errors: Off
    upload_max_filesize: 64M
    post_max_size: 64M
    zlib.output_compression: "On"
    zlib.output_compression_level: 5

  # Environment variables to use on platform.sh
  env:
    #Arguments to connect to internal database: i.e. mysql $DATABASE
    DATABASE: -h database.internal -P 3306 -u user main
    # Set NodeJS version
    NODE_VERSION: 22.14.0
    # Set NVM version
    NVM_VERSION: 0.35.2
    # Flip this switch to use in your build cmds to enable development build on platform.
    PRODUCTION: yes

crons:
  # Backup the database everyday at 8am
  # snapshot:
  #   spec: "0 8 * * *"
  #   cmd: |
  #     if [ "$PLATFORM_BRANCH" = main ]; then
  #         platform snapshot:create --yes --no-wait
  #     fi

  # Optimize the database everyday at 9am
  analyze:
    spec: "0 9 * * *"
    cmd: |
      mysqlcheck $DATABASE;
      mysqloptimize $DATABASE;
      mysqlanalyze $DATABASE;
      wp transient delete --all --quiet;

  # Force a redeploy at 10am (UTC) on the 1st and 15th of every month.
  redeploy:
    spec: "0 10 1,15 * *"
    cmd: |
      if [ "$PLATFORM_BRANCH" = main ]; then
          platform redeploy --yes --no-wait
      fi

  # Run NLP processor at 3AM every day
  process_nlp:
    spec: "0 3 * * *"
    cmd: "php web/wp-content/plugins/madden-nlp/tools/process_last_updated.php"

  # Run WordPress cron every 15 minutes
  # NOTE: DISABLE_WP_CRON has been turned on wp-config-platform.php
  # uncomment lines below to enable
  # wordpress:
  #   spec: "*/15 * * * *"
  #   cmd: |
  #     php ${PLATFORM_DOCUMENT_ROOT}/wp-cron.php

# Runtime Operations
operations:
  Trigger Rebuild:
    role: admin
    commands:
      start: git commit --allow-empty -m "Trigger rebuild or redeployment" && platform push
