<?php
namespace MaddenMedia\KrakenEvents;

use WP_Query;

class EventPages {

    public static $parentPageId = 0;
    
    public static $pages = [
        [
            'settings_label'    => 'Add Event Page',
            'settings_value'    => 'add_event',
            'default_slug'      => 'add-event',
            'default_title'     => 'Add New Event',
            'default_content'   => '<!-- wp:shortcode -->[partner_add_event_form]<!-- /wp:shortcode -->'
        ]
    ];

    public static function init() {
        //Set the parent page to the CRM dashboard if it is available
        if (Helpers::check_kraken_crm_status()) {
            self::$parentPageId = get_option('kraken_crm_page_account');
        }

        add_action('init', [__CLASS__, 'create_partner_pages']);
        add_action('wp_enqueue_scripts', [__CLASS__, 'enqueue_frontend_styles']);
        add_action('pre_get_posts', [__CLASS__, 'hide_partner_pages_search']);
    }

    public static function create_partner_pages() {        
        if (get_option('kraken_events_enable_pages')) {
            foreach(self::$pages as $page) {
                self::create_page($page);
            }
        }
    }

    private static function create_page($page) {        
        //check if we have a saved page already
        $pageCheck = get_option('kraken_events_page_'.$page['settings_value']);
        //if no page is saved in settings, create a new page
        if (empty($pageCheck)) {
            //create a new page
            $slug       = $page['default_slug']; 
            $title      = $page['default_title'];
            $content    = $page['default_content'];

            $args = [
                'post_name'     => $slug,
                'post_title'    => $title,
                'post_content'  => $content,
                'post_status'   => 'publish',
                'post_type'     => 'page',
            ];

            /*
            The main account / partner portal page will be the parent page to all other pages generated by this plugin.
            */
            if ($page['settings_value'] !== 'account' && self::$parentPageId !== 0) {
                $args['post_parent'] = self::$parentPageId;
            }

            $newId = wp_insert_post($args);

            //update the settings with the new page id
            update_option('kraken_events_page_'.$page['settings_value'], $newId);

            if ($page['settings_value'] === 'account') {
                self::$parentPageId = $newId;
            }
        }
    }

    /*
    Load front end styles on partner pages if enabled
    */
    public static function enqueue_frontend_styles() {
        $stylesEnabled = get_option('kraken_events_load_stylesheet');
        if ($stylesEnabled) {

            $pageIds    = array();      

            foreach(self::$pages as $page) {
                $pageId = get_option('kraken_events_page_'.$page['settings_value']);
                array_push($pageIds, $pageId);
            }

            if (is_page($pageIds)) {
                wp_enqueue_style(
                    'kraken-events-style',
                    plugin_dir_url(__FILE__) . '../../assets/css/style.css',
                    array(),
                    '1.0.0'
                );
            }

            $dashboard = get_option('kraken_events_page_account');
            if (is_page($dashboard)) {
                wp_enqueue_script(
                    'kraken-events-js',
                    plugin_dir_url(__FILE__) . '../../assets/js/kraken-events.js',
                    array(),
                    '1.0.0'
                );
            }
        }
    }

    /*
    Hide our partner portal pages from WordPress search queries
    */
    public static function hide_partner_pages_search($query) {
        if (!is_admin() && $query->is_main_query() && $query->is_search) {

            $exclude = array();     

            foreach(self::$pages as $page) {
                $pageId = get_option('kraken_events_page_'.$page['settings_value']);
                if ($pageId) {
                    array_push($exclude, $pageId);
                }
            }

            $query->set('post__not_in', $exclude);
        }
    }
}
