import { THEME_PREFIX } from "scripts/inc/constants";
import "./styles/style.scss";

window.addEventListener("DOMContentLoaded", () => {
	const blockSelector = ".wp-block-" + THEME_PREFIX + "-tabs";
	const uniqueId = () => `tabs-${Math.random().toString(36).substring(2, 9)}`;

	document.querySelectorAll(blockSelector).forEach((block) => {
		const navPlaceholder = block.querySelector(".tabs-nav-placeholder");
		const content = block.querySelector(".tabs-content");
		const panels = Array.from(
			content.querySelectorAll(":scope > .wp-block-" + THEME_PREFIX + "-single-tab")
		);

		if (!panels.length || !navPlaceholder) return;

		if (!block.id) {
			block.id = uniqueId();
		}

		const nav = document.createElement("div");
		nav.className = "tabs-nav";
		nav.setAttribute("role", "tablist");

		panels.forEach((panel, index) => {
			const title = panel.dataset.title || `Tab ${index + 1}`;
			const button = document.createElement("button");

			const panelId = `${block.id}-panel-${index}`;

			button.textContent = title;
			button.setAttribute("role", "tab");
			button.setAttribute("aria-controls", panelId);

			// Apply custom styles from the data attribute generated by PHP
			if (panel.dataset.customStyles) {
				button.style.cssText += panel.dataset.customStyles;
			}

			panel.setAttribute("id", panelId);
			panel.setAttribute("role", "tabpanel");
			panel.setAttribute("tabindex", "0");

			nav.appendChild(button);

			button.addEventListener("click", () => {
				// Deactivate all tabs and panels in this block
				nav.querySelectorAll("button").forEach((btn) => {
					btn.classList.remove("active");
					btn.setAttribute("aria-selected", "false");
				});
				panels.forEach((p) => p.classList.remove("active"));

				// Activate the clicked tab and its corresponding panel
				button.classList.add("active");
				button.setAttribute("aria-selected", "true");
				panel.classList.add("active");
			});

			if (index === 0) {
				button.classList.add("active");
				button.setAttribute("aria-selected", "true");
				panel.classList.add("active");
			}
		});

		navPlaceholder.replaceWith(nav);
	});
});
