#!/usr/bin/env bash
 
## Quickly deploy to dev environment 
##
## Usage: fin deploy main|stage|dev 

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------
  # Dev branch
  DEV=dev
  # Current branch
  CURRENT=$(git symbolic-ref --short HEAD)
#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------
  source ${PROJECT_ROOT}/.composer/bin/helpers
#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------
  #* fetch all branches tags and submodules
  submodules(){
    echo-green-bg "Preparing to stage branch: ${CURRENT}"
    echo-green "Fetch all branches, tags, and submodules"
    git fetch --all --tags
    fin composer run submodules
  }

  #* pull latest main and merge into current branch 
  mergeMain(){
    echo-green "Pull latest main repo"
    git pull platform main
    echo-green "Merge main into branch"
    git merge main
  }

  #* checkout staging and update to latest
  updateStaging(){
    echo-green "Checking out Staging Branch"
    git checkout ${DEV}
    echo-green "Updating to latest..."
    git pull platform ${DEV}
  }

  #* merge current branch 
  mergeCurrent(){
    echo-green "Merging branch: ${CURRENT}"
    git merge ${CURRENT}
    git push 
    git checkout ${CURRENT}
  }

  deploy(){
    # must be in root dir.
    cd ${PROJECT_ROOT}
    submodules
    mergeMain
    updateStaging
    mergeCurrent
  }
#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------
  deploy
#-------------------------- END: Execution --------------------------------