<?php
/*
$attributes; // Block attributes
$content; // Content generated by save() function
*/

/*
Uses the full size image when the cover block is set to use featured image. Fixes pixellation issues.
*/
if ('image' === $attributes['backgroundType'] && true === $attributes['useFeaturedImage']) {
	if (!( $attributes['hasParallax'] || $attributes['isRepeated'])) {
		$attr = array(
			'class'           => 'wp-block-cover__image-background',
			'data-object-fit' => 'cover',
		);

		if (isset( $attributes['focalPoint'])) {
			$object_position              = round( $attributes['focalPoint']['x'] * 100 ) . '% ' . round( $attributes['focalPoint']['y'] * 100 ) . '%';
			$attr['data-object-position'] = $object_position;
			$attr['style']                = 'object-position: ' . $object_position;
		}

		$image = get_the_post_thumbnail( null, 'full', $attr );

		/*
		* Inserts the featured image between the (1st) cover 'background' `span` and 'inner_container' `div`,
		* and removes eventual whitespace characters between the two (typically introduced at template level)
		*/
		$inner_container_start = '/<div\b[^>]+wp-block-cover__inner-container[\s|"][^>]*>/U';
		if ( 1 === preg_match( $inner_container_start, $content, $matches, PREG_OFFSET_CAPTURE ) ) {
			$offset  = $matches[0][1];
			$content = substr( $content, 0, $offset ) . $image . substr( $content, $offset );
		}
	} else {
		if ( in_the_loop() ) {
			update_post_thumbnail_cache();
		}
		$current_featured_image = get_the_post_thumbnail_url();
		if ( ! $current_featured_image ) {
			return $content;
		}

		$processor = new WP_HTML_Tag_Processor( $content );
		$processor->next_tag();

		$styles         = $processor->get_attribute( 'style' );
		$merged_styles  = ! empty( $styles ) ? $styles . ';' : '';
		$merged_styles .= 'background-image:url(' . esc_url( $current_featured_image ) . ');';

		$processor->set_attribute( 'style', $merged_styles );
		$content = $processor->get_updated_html();
	}
}

echo $content;
