<?php
/*
$attributes; // Block attributes
$content; // Content generated by save() function
$render_content; // Content generated by render_callback
*/
$service = $attributes['service'];
$icon_path = get_stylesheet_directory() . "/assets/images/icons/social/{$service}.svg";

if (file_exists($icon_path)) {
    $svg = file_get_contents($icon_path);
    
    $content = '<li class="wp-social-link wp-social-link-'.$attributes['service'].' wp-block-social-link"><a rel="noopener nofollow" target="_blank" href="'.$attributes['url'].'" class="wp-block-social-link-anchor">'.$svg.'<span class="wp-block-social-link-label screen-reader-text">'.$attributes['label'].'</span></a></li>';

    echo $content;
} else {
    echo $render_content;
}