<?php
/*
$attributes;      // Block attributes
$content;         // Content generated by save() function
$render_content;  // Content generated by render_callback
*/

$style  = $attributes['style'] ?? [];
$border = $style['border'] ?? [];

$radius = $border['radius'] ?? '';
$color  = $border['color'] ?? '';
$width  = $border['width'] ?? '';

$css_vars = [];
if ($radius) {
	if ( is_array( $radius ) ) {
		if ( isset( $radius['topLeft'] ) ) {
			$css_vars[] = "--border-top-left-radius: {$radius['topLeft']}";
		}
		if ( isset( $radius['topRight'] ) ) {
			$css_vars[] = "--border-top-right-radius: {$radius['topRight']}";
		}
		if ( isset( $radius['bottomLeft'] ) ) {
			$css_vars[] = "--border-bottom-left-radius: {$radius['bottomLeft']}";
		}
		if ( isset( $radius['bottomRight'] ) ) {
			$css_vars[] = "--border-bottom-right-radius: {$radius['bottomRight']}";
		}
	} else {
		$css_vars[] = "--border-top-left-radius: {$radius}";
		$css_vars[] = "--border-top-right-radius: {$radius}";
		$css_vars[] = "--border-bottom-left-radius: {$radius}";
		$css_vars[] = "--border-bottom-right-radius: {$radius}";
	}
}

if ($color) {
    $css_vars[] = "--border-color: {$color}";
}
if ($width) {
    $css_vars[] = "--border-width: {$width}";
}

if ($css_vars) {
    // Add inline style to the outer wp-block-image container
    $content = preg_replace(
        '/(<figure[^>]*class="[^"]*wp-block-image[^"]*"[^>]*)>/',
        '$1 style="' . esc_attr(implode('; ', $css_vars)) . '">',
        $content,
        1
    );
}

echo $content;
