<?php
/*
$attributes; // Block attributes
$content; // Content generated by save() function
$render_content; // Content generated by render_callback
*/

$block_content = $render_content ? $render_content : $content;

// Define the pattern to match the <a> tag inside any <div> with class 'wp-block-button'
$pattern = '/(<a[^>]*?class=["\'][^"\']*wp-block-read-more[^"\']*["\'][^>]*?>)(.*?)(<\/a>)/is';

// Define the replacement, wrapping the inner content with <span>
$replacement = '$1<span class="wp-block-button__text">$2</span>$3';

// Perform the replacement
$block_content = preg_replace( $pattern, $replacement, $block_content );

echo $block_content;