<?php
/*
$attributes; // Block attributes
$content; // Content generated by save() function
$render_content; // Content generated by render_callback
*/

// Define the pattern to match the <a> tag inside any <div> with class 'wp-block-button'
$pattern = '/(<div[^>]*?class=["\'][^"\']*wp-block-button[^"\']*["\'][^>]*?>\s*<a[^>]*?>)(.*?)(<\/a>\s*<\/div>)/is';

// Define the replacement, wrapping the inner content with <span>
$replacement = '$1<span class="wp-block-button__text">$2</span>$3';

// Perform the replacement
$content = preg_replace( $pattern, $replacement, $content );

echo $content;