#!/usr/bin/env bash

## Make a symlink to another file of the same dir name
##
## Usage: fin symlink TARGET_DIR(../../../../) EXT(.tpl.php) 
# Abort if anything fails

# usage on directories - for d in */; do cd $d; fin symlink "../../../../" ".tpl.php"; cd ..;  done;

TARGET_DIR=${1}
EXT=${2}

FILE=$(basename $(pwd)) 

TARGET="${TARGET_DIR}templates/vue/${FILE}${EXT}"

echo "Looking for: ${TARGET}"

if [ -f $TARGET ];then
  echo "Creating symlink: ${FILE}"
  ln -s "${TARGET}" "./${FILE}${EXT}"
else
  echo "File ${TARGET} doesn't exist"
fi