#!/usr/bin/env bash
# require-mm
# handles require madden's private repos to composer 
# @usage: composer require-mm mm-wordpress-block-example-dynamic
# @usage: composer require-mm maddenmedia/mm-wordpress-block-example-dynamic
# @version 1.2021.05.0
# @since 1.2021.5

#-------------------------- Settings --------------------------------
  # Prefix repo with maddenmedia/ - remove if already present
  REPO="maddenmedia/${1/maddenmedia\//}"
  GIT="git@github.com:${REPO}"
#-------------------------- END: Settings ---------------------------

#-------------------------- Functions --------------------------------
  requireMM(){
    composer config repositories.$REPO vcs $GIT 
    composer require $REPO 
  }
#-------------------------- END: Functions ---------------------------

#-------------------------- Execute --------------------------------
  requireMM