<?php
    use Eventastic\Library\Utilities as Utilities;
    $integratedCalendarLocation = isset( $attributes['integratedCalendarLocation'] ) ? $attributes['integratedCalendarLocation'] : 'top';
    $layoutStyle = isset( $attributes['layoutStyle'] ) ? $attributes['layoutStyle'] : 'integrated';
    $useFilters = isset( $attributes['useFilters'] ) ? $attributes['useFilters'] : true;
    $devNote = "";
    if( ( isset( $attributes['blockConfig_developerMode'] ) && $attributes['blockConfig_developerMode'] ) ){
       $devNote = "{#eventsCalendar} generated by: " . dirname(__FILE__);
    }        
?>
<?php if( $useFilters ) : ?>
    <?php if( !( "integrated" == $layoutStyle && "top" == $integratedCalendarLocation) )  : ?>
        <?php Utilities::include_template('filters' , $attributes ); ?> 
    <?php endif; ?>        
<?php endif; ?>        
<?php if( "toggled" == $layoutStyle ) : ?>
    <div class="toggle-buttons">
        <button class='has-icon active' data-target='calendar'>Calendar</button>
        <button class='has-icon' data-target='list'>List</button>        
    </div>
<?php endif; ?>
<div class="eventasticEvents active <?php echo (isset($eventsCalendarClasses) ? $eventsCalendarClasses : ""); ?>" id="eventsCalendar"  data-devNote="<?php echo $devNote; ?>">
    <?php Utilities::include_template( $layoutStyle, $attributes); ?>
</div>