<?php 
    $devNote = "";
    if( ( isset( $attributes['blockConfig_developerMode'] ) && $attributes['blockConfig_developerMode'] ) ){
        $devNote = "{.filters} generated by: " . dirname(__FILE__);
    }
?>
<?php $categoryElementType = isset($attributes['filterConfig_categoryElementType']) ? $attributes['filterConfig_categoryElementType'] : "select" ; ?>
<div class="filters" data-devNote="<?php echo $devNote; ?>">
    <?php if ( isset($attributes['filterConfig_useDates']) && $attributes['filterConfig_useDates']) : ?>
            <div class="inputWrapper">
                <label for="start_date">Start Date:</label>
                <div class="dateInput">
                    <input id="StartDate" maxlength="10" name="start_date" readonly="true" type="date" value="<?php echo date('Y-m-d'); ?>" class="eventasticDatePicker hasDatepicker">
                </div>
            </div>
            <div class="inputWrapper">
                <label for="end_date">End Date:</label>
                <div class="dateInput">
                    <input id="EndDate" maxlength="10" name="end_date" readonly="true" type="date" value="<?php echo date("Y-m-d", strtotime("+1 month", strtotime(date("Ymd")))); ?>" class="eventasticDatePicker hasDatepicker">
                </div>
            </div>
    <?php endif; ?>
    <?php if ( isset( $attributes['filterConfig_useKeyword'] ) && $attributes['filterConfig_useKeyword'] ) : ?>
            <div class="inputWrapper">
                <label for="keyword">Search By Name:</label>
                <input type="text" id="Keyword" name="keyword" value="" maxlength="50" class="keywords">
            </div>
    <?php endif; ?>
    <?php if ( isset( $attributes['filterConfig_useCategories'] ) && $attributes['filterConfig_useCategories'] ): ?>
        <?php
            $categories = [];
                if( !isset($attributes['contentConfig_categories']) || (count($attributes['contentConfig_categories']) == 1 && "all" == $attributes['contentConfig_categories'][0]) ){
                    $categories = get_terms([
                        'taxonomy' => 'eventastic_categories',
                        'hide_empty' => false,
                    ]);
                }
                else{
                    if( isset($attributes['contentConfig_categories'] )){
                        foreach( $attributes['contentConfig_categories'] as $categorySlug ){
                            $term = get_term_by('slug', $categorySlug, 'eventastic_categories');
                            if( isset($term->term_id)){
                                $categories[] = $term;
                            }
                        }
                    }
                }
            ?>
        <?php if ( $categories ): ?>

            <div class="categoryFilters">
                <div class="filterToggle">Categories:</div>
                <div class="categories">
                    <?php if ("select" == $categoryElementType): ?>
                        <select name="category" class="category-filter">
                            <option value="">All Categories</option>
                            <?php foreach ($categories as $cat): ?>
                            <option value="<?php echo $cat->slug; ?>"><?php echo $cat->name; ?></option>
                            <?php endforeach; ?>
                        </select>
                    <?php endif; ?>
                    <?php if ("buttons" == $categoryElementType): ?>
                             <?php 
                                foreach ($categories as $cat): 
                                    $img = get_field( 'category_icon', $cat->taxonomy . '_' . $cat->term_id );
                                    $img_hover = get_field( 'category_icon_hover', $cat->taxonomy . '_' . $cat->term_id );
                                ?>
                                    <button class="event-category-filter button" data-category="<?php echo $cat->slug; ?>">
                                        <span><?php echo $cat->name; ?></span>
                                        <?php if( $img && isset($img['url']) ) : ?>
                                            <img class="default-icon" src='<?php echo $img['url']; ?>'>                                        
                                        <?php endif; ?>
                                        <?php if( $img_hover && isset($img_hover['url']) ) : ?>
                                            <img class="hover-icon" src='<?php echo $img_hover['url']; ?>'>                                        
                                        <?php endif; ?>                                        
                                    </button>
                            <?php endforeach; ?>
                    <?php endif; ?>
                    <?php if ("checkboxes" == $categoryElementType): ?>
                        <?php foreach ($categories as $cat): ?>
                            <div class='checkbox-wrapper'>
                                <input type="checkbox" class="category-checkbox" name="<?php echo $cat->slug; ?>" id="<?php echo $cat->slug; ?>" value="<?php echo $cat->slug; ?>">
                                 <label for="<?php echo $cat->slug; ?>"><?php echo $cat->name; ?></label>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>                    
                </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>  
    <?php if ( isset($attributes['filterConfig_useFilterReset']) && $attributes['filterConfig_useFilterReset']) : ?>                      
        <button class="resetFilters">Reset Filter</button>
    <?php endif; ?>  
    <?php if ( isset($attributes['filterConfig_useFilterSubmit']) && $attributes['filterConfig_useFilterSubmit']) : ?>
        <button class="eventFilterSubmit">Search</button>
    <?php endif; ?>  
</div>